name: r037
favicon: null
layout_spectrum: 0.2936447844840586
typography_spectrum: 0.7490411400794983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.26597577263601124
  lightness: 0.10859935847111046
  saturation: 0.46353093604557216
  rhythmicContrast: 0.8624563843477517
purpose: []
